import { NavBar } from "@/components/layout/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
      </head>
      <body
        className={`${poppins.className} subpixel-antialiased mx-auto max-w-7xl px-4 sm:px-8 md:px-12 py-8`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
