/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MessageBoardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addMessage"
      | "getAllMessages"
      | "getMessageByIndex"
      | "getMessageCount"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MessageAdded"): EventFragment;

  encodeFunctionData(functionFragment: "addMessage", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getAllMessages",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageCount",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addMessage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageCount",
    data: BytesLike
  ): Result;
}

export namespace MessageAddedEvent {
  export type InputTuple = [user: AddressLike, message: string];
  export type OutputTuple = [user: string, message: string];
  export interface OutputObject {
    user: string;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MessageBoard extends BaseContract {
  connect(runner?: ContractRunner | null): MessageBoard;
  waitForDeployment(): Promise<this>;

  interface: MessageBoardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addMessage: TypedContractMethod<[_message: string], [void], "nonpayable">;

  getAllMessages: TypedContractMethod<[], [string[]], "view">;

  getMessageByIndex: TypedContractMethod<
    [_index: BigNumberish],
    [string],
    "view"
  >;

  getMessageCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addMessage"
  ): TypedContractMethod<[_message: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllMessages"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMessageByIndex"
  ): TypedContractMethod<[_index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getMessageCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "MessageAdded"
  ): TypedContractEvent<
    MessageAddedEvent.InputTuple,
    MessageAddedEvent.OutputTuple,
    MessageAddedEvent.OutputObject
  >;

  filters: {
    "MessageAdded(address,string)": TypedContractEvent<
      MessageAddedEvent.InputTuple,
      MessageAddedEvent.OutputTuple,
      MessageAddedEvent.OutputObject
    >;
    MessageAdded: TypedContractEvent<
      MessageAddedEvent.InputTuple,
      MessageAddedEvent.OutputTuple,
      MessageAddedEvent.OutputObject
    >;
  };
}
